select ?Count (COUNT (?Count) AS ?distribution)
WHERE{
select ?t1 (COUNT (?t1) AS ?Count)
WHere{
select ?t1
where {
 {
  ?t1 ?p1 ?t2.
  ?t2 ?p2 ?t3.
  ?t3 ?p3 ?t1.
 }
 UNION
 {
  ?t1 ?p1 ?t2.
  ?t3 ?p2 ?t2.
  ?t3 ?p3 ?t1.
 }
UNION
 {
  ?t2 ?p1 ?t1.
  ?t3 ?p2 ?t2.
  ?t3 ?p3 ?t1.
 }
UNION
 {
  ?t1 ?p1 ?t2.
  ?t3 ?p2 ?t2.
  ?t1 ?p3 ?t3.
 }
 ?t1 <%s> %s.
}

}
GROUP BY ?t1
}
GROUP BY ?Count
ORDER BY ?Count
%s